### ISSUE TITLE
swift側でpostする際，bodyをjsonで渡す仕様にしたい

### ISSUE THREAD

**Issue by alotofwe** [alotofwe/sample_app-1#10]
@takuminnnn @orzup 

現在，readmeのbodyには

```
name=xxx
hoge=xxx
```

のように適当にベタ書きされていますが，

http://qiita.com/sushichop/items/ac4ae99b905ce523c2fe

を見るとjsonでbodyを送ることができるみたいなので，
パースのしやすさのためにbodyをjsonで受け取る仕様に決めたいなと思っています．

というふうに決めていいかという相談です．

**Comment by orzup** [comment]
通信ライブラリに https://github.com/Alamofire/Alamofire をつかいたいのですが、（要議論）それでもJSONつかえるので個人的には賛成です〜 :tada:

**Comment by alotofwe** [comment]
Alamofire，ロゴが強い :fire:

**Comment by alotofwe** [comment]
では，bodyはjsonで渡されることを前提としてAPIを書きます〜
READMEをjson形式に書きかえておきます．
