### ISSUE TITLE
Gravatarの画像urlをAPIで返したい

### ISSUE THREAD

**Issue by takuminnnn** [alotofwe/sample_app-1#22]
@alotofwe 

https://github.com/alotofwe/sample_app-1/blob/master/app/helpers/users_helper.rb

iOSとの結合時に、
iOS側にGravatarの画像取得のための処理を書くのは二度手間になるので、API側でuserを渡すときに一緒に返してほしいです。

**Comment by alotofwe** [comment]
:eyes:
