### ISSUE TITLE
get 'api/users/:user_id/feed' に各ユーザの情報を追加してほしい

### ISSUE THREAD

**Issue by takuminnnn** [alotofwe/sample_app-1#30]
@alotofwe 

現在、アプリにてfeedのAPIでcontentとpictureを取ってきて表示していますが、
さらにポストしたユーザの情報も載せたいです。

### 追加してほしい情報

- name
- icon_url

**Comment by alotofwe** [comment]
micropostの情報内に入れるので，何の名前やurlなのかが分かるように，カラム名は

* user_name
* user_icon_url

にしてもいいですか...?

**Comment by takuminnnn** [comment]
なるほど。
それならネストさせたほうがわかりやすいと思うけれどどうでしょう?

```
user: {
  name: "hoge",
  icon_url: "fuga"
}
```

**Comment by alotofwe** [comment]
良い! 了解です! :clap:
